### ISSUE TITLE
Place for discussion? GH wiki?

### ISSUE THREAD

**Issue by kieran** [cyclingwithelephants/devs-on-a-boat#5]
just wanted a place to chat / discuss

for example:

Typical 27" monitors use an avg of ~30 W when on to a reasonable brightness.

MacBook Air (M1) uses about ~25 W avg when powered on, probably closer to 10W with the screen closed. Might draw 30-40 W when charging, ships with a 30W power supply but may use more when plugged into a PD supply that supports faster charging.

Mac Mini (M1) is reported to use 6.8 W idle, with a max draw of 39 W under full load. An M1 Air with a closed lid would likely be very similar, as they're effectively the same machine.

So if you use the monitor / macbook for 8h a day, that would be about ~440Wh usage. Realistically, one ~350W solar panel for 2 hours would probably comfortably cover this load.

**Comment by cyclingwithelephants** [comment]
This is a great comparison, thanks! I've opened up the Discussions feature for GH, so I suggest we move this kind of post to there if that's agreeable with yourself. 

I'm also intending to draw up a v basic kanban to track work to do, it's for anyone that wants to contribute but i'll be picking away at it as and when I can

**Comment by kieran** [comment]
[moved to discussions](https://github.com/cyclingwithelephants/devs-on-a-boat/discussions/8)
